// 100 present-tense fill-in-the-blank examples for ÊTRE and AVOIR.
// Each blank is marked with ___ in `prompt`.
// `explanation` says WHY that form is correct (subject + which verb + agreement).
//
// Present tense reference:
//   être : je suis · tu es · il/elle/on est · nous sommes · vous êtes · ils/elles sont
//   avoir: j'ai · tu as · il/elle/on a · nous avons · vous avez · ils/elles ont

const EXAMPLES = [
  // ---------- ÊTRE : je suis ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ étudiant.", translation: "I am a student.",
    explanation: "“Je” + être → suis. Être is the verb “to be”, and its first-person singular form is always “suis”." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ français.", translation: "I am French.",
    explanation: "“Je” takes “suis” with être. Nationalities use être (the state of being something)." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ fatigué aujourd'hui.", translation: "I am tired today.",
    explanation: "Describing a state (tired) uses être. With “je”, être → suis." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ à la maison.", translation: "I am at home.",
    explanation: "Location (“to be at…”) uses être. “Je” + être → suis." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ prêt à partir.", translation: "I am ready to leave.",
    explanation: "“Ready” is a state described with être. First person → suis." },

  // ---------- ÊTRE : tu es ----------
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ très gentil.", translation: "You are very kind.",
    explanation: "“Tu” + être → es. Describing a quality (kind) uses être." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ en retard.", translation: "You are late.",
    explanation: "“To be late” = être en retard. With “tu”, être → es." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ mon meilleur ami.", translation: "You are my best friend.",
    explanation: "Identifying who someone is uses être. “Tu” → es." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ là ?", translation: "Are you there?",
    explanation: "Presence/location uses être. Second-person singular “tu” → es." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ sûr de toi.", translation: "You are sure of yourself.",
    explanation: "A state of mind (sure) uses être. “Tu” + être → es." },

  // ---------- ÊTRE : il / elle / on est ----------
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ médecin.", translation: "He is a doctor.",
    explanation: "“Il” + être → est. Professions take être with no article (il est médecin)." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle ___ belle.", translation: "She is beautiful.",
    explanation: "“Elle” is third-person singular, so être → est. Adjectives of quality use être." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ en vacances !", translation: "We're on vacation!",
    explanation: "“On” behaves like il/elle (singular), so être → est, even though it means “we” here." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ trois heures.", translation: "It is three o'clock.",
    explanation: "Telling time uses “il est” + the hour. Impersonal “il” → est." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle ___ à Paris cette semaine.", translation: "She is in Paris this week.",
    explanation: "Location uses être. “Elle” (singular) → est." },
  { verb: "être", subject: "Ce", answer: "est", prompt: "C'___ une bonne idée.", translation: "It's a good idea.",
    explanation: "“C'est” (ce + est) identifies/defines something. Ce is singular → est." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ d'accord.", translation: "We agree.",
    explanation: "“Être d'accord” = to agree. “On” conjugates like il/elle → est." },

  // ---------- ÊTRE : nous sommes ----------
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ amis depuis longtemps.", translation: "We have been friends for a long time.",
    explanation: "“Nous” + être → sommes. The nous form of être is irregular: sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ en France.", translation: "We are in France.",
    explanation: "Location uses être. First-person plural “nous” → sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ contents de te voir.", translation: "We are happy to see you.",
    explanation: "Emotion/state (happy) uses être. “Nous” → sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ prêts.", translation: "We are ready.",
    explanation: "Describing readiness uses être. “Nous” + être → sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ lundi aujourd'hui.", translation: "Today is Monday.",
    explanation: "Days of the week can use “nous sommes” (nous sommes lundi). Nous → sommes." },

  // ---------- ÊTRE : vous êtes ----------
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ très aimable.", translation: "You are very kind. (formal)",
    explanation: "“Vous” + être → êtes (note the circumflex). Used for formal “you” or plural." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ les bienvenus.", translation: "You are welcome (here).",
    explanation: "Plural/formal “vous” + être → êtes." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ professeur ?", translation: "Are you a teacher?",
    explanation: "Profession uses être. Formal “vous” → êtes." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Où ___-vous ?", translation: "Where are you?",
    explanation: "Location question uses être. “Vous” → êtes (vous êtes → êtes-vous when inverted)." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ en avance.", translation: "You are early.",
    explanation: "“Être en avance” = to be early. “Vous” → êtes." },

  // ---------- ÊTRE : ils / elles sont ----------
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ américains.", translation: "They are American.",
    explanation: "“Ils” (they, masc./mixed) + être → sont. Nationalities use être." },
  { verb: "être", subject: "Elles", answer: "sont", prompt: "Elles ___ sœurs.", translation: "They are sisters.",
    explanation: "“Elles” (they, fem.) + être → sont. Relationships/identity use être." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Les clés ___ sur la table.", translation: "The keys are on the table.",
    explanation: "“Les clés” is plural (they), so être → sont. Location uses être." },
  { verb: "être", subject: "Elles", answer: "sont", prompt: "Elles ___ en réunion.", translation: "They are in a meeting.",
    explanation: "Plural subject + être → sont. Being somewhere uses être." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ très occupés.", translation: "They are very busy.",
    explanation: "Describing a state (busy) for a plural subject → sont." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Mes parents ___ en voyage.", translation: "My parents are traveling.",
    explanation: "“Mes parents” = plural (ils), so être → sont." },

  // ---------- AVOIR : j'ai ----------
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ un chien.", translation: "I have a dog.",
    explanation: "“J'” + avoir → ai. Possession uses avoir. Je becomes j' before a vowel." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ deux frères.", translation: "I have two brothers.",
    explanation: "Avoir = to have. First person j' → ai." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ une question.", translation: "I have a question.",
    explanation: "“Avoir une question” = to have a question. J' → ai." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ vingt ans.", translation: "I am twenty years old.",
    explanation: "Age uses AVOIR in French, not être: “avoir … ans”. So j'ai, literally “I have 20 years.”" },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ faim.", translation: "I am hungry.",
    explanation: "Hunger uses avoir: “avoir faim” (literally “to have hunger”). J' → ai." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ froid.", translation: "I am cold.",
    explanation: "“Avoir froid” = to be cold (lit. “to have cold”). French uses avoir for this, so j'ai." },

  // ---------- AVOIR : tu as ----------
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ raison.", translation: "You are right.",
    explanation: "“Avoir raison” = to be right (lit. “to have reason”). “Tu” + avoir → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ une belle voiture.", translation: "You have a nice car.",
    explanation: "Possession uses avoir. “Tu” → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ soif ?", translation: "Are you thirsty?",
    explanation: "“Avoir soif” = to be thirsty. With “tu”, avoir → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ le temps ?", translation: "Do you have time?",
    explanation: "Possession of time uses avoir. “Tu” → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ de la chance.", translation: "You are lucky.",
    explanation: "“Avoir de la chance” = to be lucky (lit. “to have luck”). “Tu” → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ peur du noir.", translation: "You are afraid of the dark.",
    explanation: "“Avoir peur” = to be afraid. French uses avoir, so “tu” → as." },

  // ---------- AVOIR : il / elle / on a ----------
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ les yeux bleus.", translation: "He has blue eyes.",
    explanation: "“Il” + avoir → a. Physical features (having eyes/hair) use avoir." },
  { verb: "avoir", subject: "Elle", answer: "a", prompt: "Elle ___ un bon travail.", translation: "She has a good job.",
    explanation: "Possession uses avoir. “Elle” (singular) → a." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ un examen demain.", translation: "We have an exam tomorrow.",
    explanation: "“On” conjugates like il/elle, so avoir → a, even though it means “we”." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ dix ans.", translation: "He is ten years old.",
    explanation: "Age uses avoir (“avoir … ans”). “Il” → a." },
  { verb: "avoir", subject: "Elle", answer: "a", prompt: "Elle ___ mal à la tête.", translation: "She has a headache.",
    explanation: "“Avoir mal à…” = to have pain / ache. “Elle” → a." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il y ___ un problème.", translation: "There is a problem.",
    explanation: "“Il y a” = there is/are — a fixed expression built on avoir. Impersonal “il” → a." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ besoin d'aide.", translation: "We need help.",
    explanation: "“Avoir besoin de” = to need. “On” conjugates like il/elle → a." },

  // ---------- AVOIR : nous avons ----------
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ une grande famille.", translation: "We have a big family.",
    explanation: "“Nous” + avoir → avons. Possession uses avoir." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ cours à huit heures.", translation: "We have class at eight.",
    explanation: "Having a scheduled thing uses avoir. “Nous” → avons." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ envie de sortir.", translation: "We feel like going out.",
    explanation: "“Avoir envie de” = to feel like / want. “Nous” → avons." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ assez d'argent.", translation: "We have enough money.",
    explanation: "Possession uses avoir. First-person plural “nous” → avons." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ chaud ici.", translation: "We are hot here.",
    explanation: "“Avoir chaud” = to be hot (lit. “to have heat”). “Nous” → avons." },

  // ---------- AVOIR : vous avez ----------
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ des enfants ?", translation: "Do you have children?",
    explanation: "“Vous” + avoir → avez. Possession uses avoir." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ l'heure ?", translation: "Do you have the time?",
    explanation: "Asking for the time uses avoir (“avoir l'heure”). “Vous” → avez." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ raison.", translation: "You are right.",
    explanation: "“Avoir raison” = to be right. Formal/plural “vous” → avez." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ rendez-vous à midi.", translation: "You have an appointment at noon.",
    explanation: "“Avoir rendez-vous” = to have an appointment. “Vous” → avez." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ de la patience.", translation: "You have patience.",
    explanation: "Possession of a quality uses avoir. “Vous” → avez." },

  // ---------- AVOIR : ils / elles ont ----------
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ une maison à la campagne.", translation: "They have a house in the country.",
    explanation: "“Ils” + avoir → ont. Possession uses avoir. (Careful: ils ONT = have, ils SONT = are.)" },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ beaucoup d'amis.", translation: "They have a lot of friends.",
    explanation: "Plural subject + avoir → ont. Don't confuse with “sont” (être)." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ sommeil.", translation: "They are sleepy.",
    explanation: "“Avoir sommeil” = to be sleepy. Third-person plural avoir → ont." },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ trente ans.", translation: "They are thirty years old.",
    explanation: "Age uses avoir (“avoir … ans”). “Elles” → ont." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Les enfants ___ faim.", translation: "The children are hungry.",
    explanation: "“Les enfants” is plural (ils), and “avoir faim” = to be hungry. → ont." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Mes voisins ___ un chat.", translation: "My neighbors have a cat.",
    explanation: "“Mes voisins” = plural (ils). Possession uses avoir → ont." },

  // ---------- MIXED / contrast être vs avoir (the tricky part) ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ content.", translation: "I am happy.",
    explanation: "“Content” is an adjective describing a state → être. “Je” → suis. (Compare: j'ai = I have.)" },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ chaud.", translation: "I am hot.",
    explanation: "Even though English says “I am hot”, French uses avoir for body sensations: “avoir chaud”. J' → ai." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ malade.", translation: "He is sick.",
    explanation: "“Malade” (sick) is a state described with être. “Il” → est." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ de la fièvre.", translation: "He has a fever.",
    explanation: "Having a symptom uses avoir. “Il” → a. (He IS sick = il est malade; he HAS a fever = il a de la fièvre.)" },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ en bonne santé.", translation: "We are in good health.",
    explanation: "“Être en bonne santé” = to be healthy (a state) → être. “Nous” → sommes." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ tort.", translation: "You are wrong.",
    explanation: "“Avoir tort” = to be wrong (lit. “to have wrong”). French uses avoir → “tu” → as." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ en colère ?", translation: "Are you angry?",
    explanation: "“Être en colère” = to be angry (a state) → être. “Vous” → êtes. (But “avoir peur” uses avoir!)" },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ honte.", translation: "They are ashamed.",
    explanation: "“Avoir honte” = to be ashamed. Like many feelings, French uses avoir → ont." },

  // ---------- More variety, all persons ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ désolé.", translation: "I am sorry.",
    explanation: "“Désolé” describes how you are → être. First person → suis." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ besoin de toi.", translation: "I need you.",
    explanation: "“Avoir besoin de” = to need. J' → ai." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ courageux.", translation: "You are brave.",
    explanation: "A character trait (brave) uses être. “Tu” → es." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ les cheveux longs.", translation: "You have long hair.",
    explanation: "Describing physical features uses avoir. “Tu” → as." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle ___ intelligente.", translation: "She is intelligent.",
    explanation: "A quality (intelligent) uses être. “Elle” → est." },
  { verb: "avoir", subject: "Elle", answer: "a", prompt: "Elle ___ un nouveau téléphone.", translation: "She has a new phone.",
    explanation: "Possession uses avoir. “Elle” → a." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ prêts à commencer.", translation: "We are ready to start.",
    explanation: "“On” conjugates like il/elle → est. Readiness is a state → être." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ le temps.", translation: "We have time.",
    explanation: "Possession uses avoir. “On” → a (like il/elle)." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ français.", translation: "We are French.",
    explanation: "Nationality uses être. “Nous” → sommes." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ peur des araignées.", translation: "We are afraid of spiders.",
    explanation: "“Avoir peur (de)” = to be afraid (of). “Nous” → avons." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ sûrs ?", translation: "Are you sure? (plural)",
    explanation: "Certainty (“être sûr”) is a state → être. Plural “vous” → êtes." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ tort.", translation: "You are wrong.",
    explanation: "“Avoir tort” = to be wrong. “Vous” → avez." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ en forme.", translation: "They are in good shape.",
    explanation: "“Être en forme” = to be fit. Plural → sont." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ rendez-vous chez le médecin.", translation: "They have a doctor's appointment.",
    explanation: "“Avoir rendez-vous” uses avoir. Plural “ils” → ont." },

  // ---------- Common everyday lines ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ ici depuis ce matin.", translation: "I have been here since this morning.",
    explanation: "Presence/location uses être. “Je” → suis." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ mal aux dents.", translation: "I have a toothache.",
    explanation: "“Avoir mal à…” = to have an ache. J' → ai." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ de retour !", translation: "You're back!",
    explanation: "“Être de retour” = to be back. “Tu” → es." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ un message.", translation: "You have a message.",
    explanation: "Possession uses avoir. “Tu” → as." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ tard.", translation: "It is late.",
    explanation: "“Il est tard” — impersonal “il” + être → est for time/conditions." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ raison cette fois.", translation: "He is right this time.",
    explanation: "“Avoir raison” = to be right. “Il” → a." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ presque arrivés.", translation: "We have almost arrived.",
    explanation: "“Être arrivé” describes a state of arrival → être. “Nous” → sommes." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ deux chats.", translation: "We have two cats.",
    explanation: "Possession uses avoir. “Nous” → avons." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ d'où ?", translation: "Where are you from?",
    explanation: "Origin uses être (“être de…”). “Vous” → êtes." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ faim ?", translation: "Are you hungry?",
    explanation: "“Avoir faim” = to be hungry. “Vous” → avez." },
  { verb: "être", subject: "Elles", answer: "sont", prompt: "Elles ___ jumelles.", translation: "They are twins.",
    explanation: "Identity uses être. “Elles” → sont." },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ cours de français.", translation: "They have French class.",
    explanation: "Having a class uses avoir. “Elles” → ont." },

  // ---------- A few more ÊTRE to round out ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ d'accord avec toi.", translation: "I agree with you.",
    explanation: "“Être d'accord” = to agree. “Je” → suis." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ libre ce soir ?", translation: "Are you free tonight?",
    explanation: "Availability (“être libre”) is a state → être. “Tu” → es." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Le café ___ chaud.", translation: "The coffee is hot.",
    explanation: "An object's temperature as a state uses être. “Le café” (it) → est." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ en train de manger.", translation: "We are eating (right now).",
    explanation: "“Être en train de” = to be in the middle of doing. “Nous” → sommes." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ prêts ?", translation: "Are you ready? (plural)",
    explanation: "Readiness is a state → être. Plural “vous” → êtes." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ déjà partis.", translation: "They have already left.",
    explanation: "“Partir” forms its passé composé with être: ils sont partis. Plural → sont." },

  // ---------- A few more AVOIR to round out ----------
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ sommeil.", translation: "I am sleepy.",
    explanation: "“Avoir sommeil” = to be sleepy. J' → ai." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ quel âge ?", translation: "How old are you?",
    explanation: "Age uses avoir (“avoir … ans”). “Tu” → as." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ beaucoup de travail.", translation: "He has a lot of work.",
    explanation: "Possession (of work) uses avoir. “Il” → a." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ un cadeau pour toi.", translation: "We have a gift for you.",
    explanation: "Possession uses avoir. “Nous” → avons." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ de la chance !", translation: "You are lucky!",
    explanation: "“Avoir de la chance” = to be lucky. “Vous” → avez." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ besoin de repos.", translation: "They need rest.",
    explanation: "“Avoir besoin de” = to need. Plural “ils” → ont." },

  // ---------- Final contrast pairs (être vs avoir confusion) ----------
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ étudiants.", translation: "They are students.",
    explanation: "Identity/role uses être → sont. (Watch out: ils SONT = are, ils ONT = have.)" },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ des devoirs.", translation: "They have homework.",
    explanation: "Possession uses avoir → ont. Compare with “sont” (être) above — only one letter differs!" },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ samedi.", translation: "It's Saturday.",
    explanation: "Stating the day uses être (“on est samedi”). “On” → est." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ gagné !", translation: "We won!",
    explanation: "“Gagner” forms its passé composé with avoir: on a gagné. “On” → a." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ né en hiver.", translation: "I was born in winter.",
    explanation: "“Naître” (to be born) uses être in the passé composé: je suis né. “Je” → suis." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ mangé une pomme.", translation: "I ate an apple.",
    explanation: "Most verbs (like manger) form the passé composé with avoir: j'ai mangé. J' → ai." },

  // ---------- NEGATIVES: ne … pas (n' before a vowel) ----------
  // The verb form is unchanged — it's just wrapped in ne … pas.
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ne ___ pas fatigué.", translation: "I am not tired.",
    explanation: "Negation wraps the verb: ne + verb + pas. The form is still “je suis” → Je ne suis pas. (ne stays full before the consonant of “suis”.)" },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu n'___ pas en retard.", translation: "You are not late.",
    explanation: "ne becomes n' before a vowel, and “es” starts with a vowel → Tu n'es pas. The verb form is unchanged." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il n'___ pas content.", translation: "He is not happy.",
    explanation: "n' + est + pas → Il n'est pas. ne elides to n' before the vowel of “est”." },
  { verb: "être", subject: "Ce", answer: "est", prompt: "Ce n'___ pas vrai.", translation: "It's not true.",
    explanation: "“Ce n'est pas” is the negative of “c'est”. ne → n' before “est”." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ne ___ pas prêts.", translation: "We are not ready.",
    explanation: "ne + sommes + pas → Nous ne sommes pas. ne stays full before the consonant of “sommes”." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous n'___ pas sûrs.", translation: "You are not sure.",
    explanation: "“êtes” starts with a vowel, so ne → n' → Vous n'êtes pas." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ne ___ pas américains.", translation: "They are not American.",
    explanation: "ne + sont + pas → Ils ne sont pas. The form “sont” doesn't change in the negative." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle n'___ pas là.", translation: "She is not here.",
    explanation: "n' + est + pas → Elle n'est pas là." },

  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "Je n'___ pas faim.", translation: "I am not hungry.",
    explanation: "All present-tense avoir forms start with a vowel, so ne → n': Je n'ai pas faim." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu n'___ pas raison.", translation: "You are not right.",
    explanation: "n' + as + pas → Tu n'as pas raison. The verb form stays “as”." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il n'___ pas de voiture.", translation: "He doesn't have a car.",
    explanation: "Il n'a pas… Note: after a negative, un/une/des become “de” — “une voiture” → “pas de voiture”." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On n'___ pas peur.", translation: "We're not afraid.",
    explanation: "“On” conjugates like il/elle → a, and ne → n' before it: On n'a pas peur." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous n'___ pas le temps.", translation: "We don't have time.",
    explanation: "n' + avons + pas → Nous n'avons pas le temps." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous n'___ pas tort.", translation: "You are not wrong.",
    explanation: "n' + avez + pas → Vous n'avez pas tort." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils n'___ pas d'enfants.", translation: "They don't have children.",
    explanation: "Ils n'ont pas… After a negative, “des” becomes “de” (→ d' before a vowel): “des enfants” → “pas d'enfants”." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "Je n'___ pas de chien.", translation: "I don't have a dog.",
    explanation: "Je n'ai pas… and “un chien” → “pas de chien” (un/une/des → de in the negative)." },

  // ---------- ON: conjugates like il/elle, but usually means "we" ----------
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ en retard !", translation: "We're late!",
    explanation: "“On” takes the same form as il/elle (3rd-person singular) → est, even though it means “we” here." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ ensemble.", translation: "We're together.",
    explanation: "“On” conjugates like il/elle → est. It's grammatically singular." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ prêts ?", translation: "Are we ready?",
    explanation: "“On” → est (like il/elle). The adjective “prêts” can take a plural ending because “on” means several people." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ contents pour toi.", translation: "We're happy for you.",
    explanation: "Emotion uses être, and “on” conjugates like il/elle → est." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ presque arrivés.", translation: "We've almost arrived.",
    explanation: "“On” → est (3rd-person singular form), even though it stands in for “nous” (we)." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ faim.", translation: "We're hungry.",
    explanation: "“Avoir faim” = to be hungry, and “on” conjugates like il/elle → a." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ besoin de toi.", translation: "We need you.",
    explanation: "“Avoir besoin de” = to need. “On” → a (same form as il/elle)." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ de la chance.", translation: "We're lucky.",
    explanation: "“Avoir de la chance” = to be lucky. “On” → a, like il/elle." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ rendez-vous à midi.", translation: "We have an appointment at noon.",
    explanation: "“Avoir rendez-vous” uses avoir. “On” conjugates like il/elle → a." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On n'___ pas cours demain.", translation: "We don't have class tomorrow.",
    explanation: "“On” → a (like il/elle), and in the negative ne elides to n' before it: On n'a pas cours." },

  // ---------- MULTI-VERB: two blanks in one sentence ----------
  // Mixed être + avoir
  { prompt: "Ils ___ étudiants et ils ___ beaucoup de devoirs.", translation: "They are students and they have a lot of homework.",
    blanks: [ { verb: "être", answer: "sont" }, { verb: "avoir", answer: "ont" } ],
    explanation: "Identity uses être → ils sont; possession uses avoir → ils ont. Watch the trap: sont (are) vs ont (have) differ by one letter." },
  { prompt: "Tu ___ raison, tu ___ très intelligent.", translation: "You are right, you are very smart.",
    blanks: [ { verb: "avoir", answer: "as" }, { verb: "être", answer: "es" } ],
    explanation: "“Avoir raison” = to be right → tu as. But “intelligent” is a quality → être → tu es. Same English “you are”, two different French verbs." },
  { prompt: "Vous ___ en retard parce que vous ___ trop de travail.", translation: "You're late because you have too much work.",
    blanks: [ { verb: "être", answer: "êtes" }, { verb: "avoir", answer: "avez" } ],
    explanation: "“Être en retard” → vous êtes; possession of work uses avoir → vous avez." },
  { prompt: "Il ___ malade parce qu'il ___ froid.", translation: "He is sick because he is cold.",
    blanks: [ { verb: "être", answer: "est" }, { verb: "avoir", answer: "a" } ],
    explanation: "“Malade” is a state → être → il est. But “avoir froid” (to be cold) uses avoir → il a. English uses “is” for both." },
  { prompt: "Nous ___ contents parce que nous ___ un nouveau bébé.", translation: "We're happy because we have a new baby.",
    blanks: [ { verb: "être", answer: "sommes" }, { verb: "avoir", answer: "avons" } ],
    explanation: "Emotion uses être → nous sommes; possession uses avoir → nous avons." },
  { prompt: "Quand j'___ faim, je ___ de mauvaise humeur.", translation: "When I'm hungry, I'm in a bad mood.",
    blanks: [ { verb: "avoir", answer: "ai" }, { verb: "être", answer: "suis" } ],
    explanation: "“Avoir faim” = to be hungry → j'ai. “Être de mauvaise humeur” = to be in a bad mood → je suis." },
  { prompt: "Elle n'___ pas contente parce qu'elle ___ faim.", translation: "She's not happy because she's hungry.",
    blanks: [ { verb: "être", answer: "est" }, { verb: "avoir", answer: "a" } ],
    explanation: "“Contente” is a state → être → elle n'est pas. “Avoir faim” uses avoir → elle a faim." },
  { prompt: "Je ___ là, mais je n'___ pas le temps.", translation: "I'm here, but I don't have time.",
    blanks: [ { verb: "être", answer: "suis" }, { verb: "avoir", answer: "ai" } ],
    explanation: "Presence uses être → je suis; possession of time uses avoir → je n'ai pas le temps." },
  // Double avoir
  { prompt: "J'___ faim et j'___ soif.", translation: "I'm hungry and I'm thirsty.",
    blanks: [ { verb: "avoir", answer: "ai" }, { verb: "avoir", answer: "ai" } ],
    explanation: "Both “avoir faim” and “avoir soif” use avoir → j'ai both times. English says “I'm”, but French uses avoir (to have)." },
  { prompt: "Tu ___ vingt ans et tu ___ déjà un bon travail.", translation: "You're twenty and you already have a good job.",
    blanks: [ { verb: "avoir", answer: "as" }, { verb: "avoir", answer: "as" } ],
    explanation: "Age uses avoir → tu as … ans; possession uses avoir → tu as un travail. Both avoir → as." },
  { prompt: "Ils ___ faim mais ils n'___ pas le temps de manger.", translation: "They're hungry but they don't have time to eat.",
    blanks: [ { verb: "avoir", answer: "ont" }, { verb: "avoir", answer: "ont" } ],
    explanation: "“Avoir faim” and “avoir le temps” both use avoir → ils ont / ils n'ont pas. The negative wraps the second one." },
  // Double être
  { prompt: "Je ___ fatigué parce que je ___ malade.", translation: "I'm tired because I'm sick.",
    blanks: [ { verb: "être", answer: "suis" }, { verb: "être", answer: "suis" } ],
    explanation: "“Fatigué” and “malade” are both states → être → je suis both times." },
  { prompt: "Elle ___ médecin et elle ___ très gentille.", translation: "She is a doctor and she is very kind.",
    blanks: [ { verb: "être", answer: "est" }, { verb: "être", answer: "est" } ],
    explanation: "Profession and quality both use être → elle est both times." },
  { prompt: "Nous ___ français mais nous ne ___ pas de Paris.", translation: "We are French but we're not from Paris.",
    blanks: [ { verb: "être", answer: "sommes" }, { verb: "être", answer: "sommes" } ],
    explanation: "Nationality and origin both use être → nous sommes / nous ne sommes pas." },

  // ====================================================================
  // REGULAR -ER VERBS (1st conjugation)
  // Drop -er → stem, then add: je -e · tu -es · il/elle/on -e ·
  //   nous -ons · vous -ez · ils/elles -ent.
  // Trap: the je, tu, il and ils forms (parle, parles, parle, parlent)
  //   all sound IDENTICAL — the endings -e/-es/-ent are silent.
  // ====================================================================

  // ---------- PARLER : to speak ----------
  { verb: "parler", subject: "Je", answer: "parle", prompt: "Je ___ français.", translation: "I speak French.",
    explanation: "Regular -er verb: parler → drop -er → stem “parl-”, add the je ending -e → je parle. The -e is silent." },
  { verb: "parler", subject: "Tu", answer: "parles", prompt: "Tu ___ trop vite.", translation: "You speak too fast.",
    explanation: "Stem “parl-” + the tu ending -es → tu parles. It sounds exactly like “je parle” — the -es is silent." },
  { verb: "parler", subject: "Nous", answer: "parlons", prompt: "Nous ___ de toi.", translation: "We're talking about you.",
    explanation: "The nous ending of every -er verb is -ons → nous parlons. This one you can hear (“-ons”)." },
  { verb: "parler", subject: "Vous", answer: "parlez", prompt: "Vous ___ anglais ?", translation: "Do you speak English?",
    explanation: "The vous ending of every -er verb is -ez → vous parlez. Audible too (“-ez”)." },
  { verb: "parler", subject: "Je", answer: "parle", prompt: "Je ne ___ pas espagnol.", translation: "I don't speak Spanish.",
    explanation: "Negation wraps the verb (ne … pas) but doesn't change its form: je parle → je ne parle pas." },

  // ---------- AIMER : to like / to love ----------
  { verb: "aimer", subject: "Je (j')", answer: "aime", prompt: "J'___ le chocolat.", translation: "I like chocolate.",
    explanation: "Stem “aim-” + je ending -e → j'aime. Je becomes j' before the vowel of “aime”." },
  { verb: "aimer", subject: "Tu", answer: "aimes", prompt: "Tu ___ la musique.", translation: "You like music.",
    explanation: "Stem “aim-” + tu ending -es → tu aimes. Sounds the same as j'aime." },
  { verb: "aimer", subject: "Elle", answer: "aime", prompt: "Elle ___ danser.", translation: "She likes to dance.",
    explanation: "il/elle/on ending is -e → elle aime. A second verb after aimer stays in the infinitive (danser)." },
  { verb: "aimer", subject: "Nous", answer: "aimons", prompt: "Nous ___ voyager.", translation: "We like to travel.",
    explanation: "nous ending -ons → nous aimons. Followed by the infinitive “voyager”." },
  { verb: "aimer", subject: "Ils", answer: "aiment", prompt: "Ils ___ le football.", translation: "They like soccer.",
    explanation: "ils/elles ending is -ent → ils aiment. The -ent is completely silent: “aiment” sounds like “aime”." },

  // ---------- HABITER : to live (somewhere) ----------
  { verb: "habiter", subject: "Je (j')", answer: "habite", prompt: "J'___ à Paris.", translation: "I live in Paris.",
    explanation: "Stem “habit-” + -e → j'habite. The h is silent, so je elides to j'." },
  { verb: "habiter", subject: "Tu", answer: "habites", prompt: "Tu ___ où ?", translation: "Where do you live?",
    explanation: "Stem “habit-” + tu ending -es → tu habites." },
  { verb: "habiter", subject: "Il", answer: "habite", prompt: "Il ___ avec ses parents.", translation: "He lives with his parents.",
    explanation: "il ending -e → il habite. (No liaison needed in writing — just the silent -e.)" },
  { verb: "habiter", subject: "Nous", answer: "habitons", prompt: "Nous ___ en France.", translation: "We live in France.",
    explanation: "nous ending -ons → nous habitons." },
  { verb: "habiter", subject: "Elles", answer: "habitent", prompt: "Elles ___ ensemble.", translation: "They live together.",
    explanation: "elles ending -ent → elles habitent. The -ent is silent." },

  // ---------- TRAVAILLER : to work ----------
  { verb: "travailler", subject: "Je", answer: "travaille", prompt: "Je ___ beaucoup.", translation: "I work a lot.",
    explanation: "Stem “travaill-” + -e → je travaille." },
  { verb: "travailler", subject: "Tu", answer: "travailles", prompt: "Tu ___ aujourd'hui ?", translation: "Are you working today?",
    explanation: "Stem “travaill-” + tu ending -es → tu travailles." },
  { verb: "travailler", subject: "On", answer: "travaille", prompt: "On ___ ensemble.", translation: "We work together.",
    explanation: "“On” conjugates like il/elle → ending -e → on travaille, even though it means “we”." },
  { verb: "travailler", subject: "Vous", answer: "travaillez", prompt: "Vous ___ ici ?", translation: "Do you work here?",
    explanation: "vous ending -ez → vous travaillez." },
  { verb: "travailler", subject: "Ils", answer: "travaillent", prompt: "Ils ne ___ pas le dimanche.", translation: "They don't work on Sundays.",
    explanation: "ils ending -ent → ils travaillent; the negative ne … pas wraps it without changing the form." },

  // ---------- REGARDER : to watch / to look at ----------
  { verb: "regarder", subject: "Je", answer: "regarde", prompt: "Je ___ la télé.", translation: "I'm watching TV.",
    explanation: "Stem “regard-” + -e → je regarde. French present covers “I watch” and “I'm watching”." },
  { verb: "regarder", subject: "Tu", answer: "regardes", prompt: "Tu ___ un film.", translation: "You're watching a movie.",
    explanation: "Stem “regard-” + tu ending -es → tu regardes." },
  { verb: "regarder", subject: "Elle", answer: "regarde", prompt: "Elle ___ par la fenêtre.", translation: "She's looking out the window.",
    explanation: "elle ending -e → elle regarde. (regarder = to look AT, no “à” needed.)" },
  { verb: "regarder", subject: "Nous", answer: "regardons", prompt: "Nous ___ le match.", translation: "We're watching the game.",
    explanation: "nous ending -ons → nous regardons." },
  { verb: "regarder", subject: "Ils", answer: "regardent", prompt: "Ils ___ les étoiles.", translation: "They're looking at the stars.",
    explanation: "ils ending -ent → ils regardent. Silent ending — sounds like “regarde”." },

  // ---------- ÉCOUTER : to listen (to) ----------
  { verb: "écouter", subject: "Je (j')", answer: "écoute", prompt: "J'___ de la musique.", translation: "I'm listening to music.",
    explanation: "Stem “écout-” + -e → j'écoute. (écouter = to listen TO, no “à” needed.)" },
  { verb: "écouter", subject: "Tu", answer: "écoutes", prompt: "Tu ___ le professeur.", translation: "You listen to the teacher.",
    explanation: "Stem “écout-” + tu ending -es → tu écoutes." },
  { verb: "écouter", subject: "On", answer: "écoute", prompt: "On ___ la radio.", translation: "We listen to the radio.",
    explanation: "“On” takes the il/elle form → ending -e → on écoute." },
  { verb: "écouter", subject: "Vous", answer: "écoutez", prompt: "Vous ___ bien ?", translation: "Are you listening carefully?",
    explanation: "vous ending -ez → vous écoutez." },
  { verb: "écouter", subject: "Elles", answer: "écoutent", prompt: "Elles ___ une chanson.", translation: "They're listening to a song.",
    explanation: "elles ending -ent → elles écoutent. The -ent is silent." },

  // ---------- CHERCHER : to look for / to search ----------
  { verb: "chercher", subject: "Je", answer: "cherche", prompt: "Je ___ mes clés.", translation: "I'm looking for my keys.",
    explanation: "Stem “cherch-” + -e → je cherche. (chercher = to look FOR; “for” is already inside the verb.)" },
  { verb: "chercher", subject: "Tu", answer: "cherches", prompt: "Tu ___ du travail ?", translation: "Are you looking for work?",
    explanation: "Stem “cherch-” + tu ending -es → tu cherches." },
  { verb: "chercher", subject: "Il", answer: "cherche", prompt: "Il ___ son chien.", translation: "He's looking for his dog.",
    explanation: "il ending -e → il cherche." },
  { verb: "chercher", subject: "Nous", answer: "cherchons", prompt: "Nous ___ un restaurant.", translation: "We're looking for a restaurant.",
    explanation: "nous ending -ons → nous cherchons." },
  { verb: "chercher", subject: "Ils", answer: "cherchent", prompt: "Ils ___ la sortie.", translation: "They're looking for the exit.",
    explanation: "ils ending -ent → ils cherchent. Silent ending." },

  // ---------- JOUER : to play ----------
  { verb: "jouer", subject: "Je", answer: "joue", prompt: "Je ___ au tennis.", translation: "I play tennis.",
    explanation: "Stem “jou-” + -e → je joue. “jouer à” for sports/games (au = à + le)." },
  { verb: "jouer", subject: "Tu", answer: "joues", prompt: "Tu ___ du piano.", translation: "You play the piano.",
    explanation: "Stem “jou-” + tu ending -es → tu joues. “jouer de” for instruments (du = de + le)." },
  { verb: "jouer", subject: "On", answer: "joue", prompt: "On ___ dans le parc.", translation: "We play in the park.",
    explanation: "“On” takes the il/elle form → ending -e → on joue." },
  { verb: "jouer", subject: "Vous", answer: "jouez", prompt: "Vous ___ aux cartes ?", translation: "Do you play cards?",
    explanation: "vous ending -ez → vous jouez. (aux = à + les.)" },
  { verb: "jouer", subject: "Ils", answer: "jouent", prompt: "Les enfants ___ dehors.", translation: "The children are playing outside.",
    explanation: "“Les enfants” is plural (ils) → ending -ent → jouent. Silent ending — sounds like “joue”." },

  // ====================================================================
  // POSSESSIVE ADJECTIVES  (mon/ma/mes · ton/ta/tes · son/sa/ses ·
  //                         notre/nos · votre/vos · leur/leurs)
  // Two ideas at once:
  //   1) WHO owns it  → which set (mon = my, ton = your, son = his/her, …)
  //   2) the NOUN     → which ending (masc sing / fem sing / plural)
  // son/sa/ses agree with the NOUN, not the owner: “sa voiture” = his OR her car.
  // notre/votre/leur have no masc/fem form — only singular vs plural (nos/vos/leurs).
  // Trap: before a vowel or silent h, a feminine noun takes the MASCULINE form:
  //   mon amie, ton école, son histoire.
  // ====================================================================

  // ---------- MON / MA / MES : my ----------
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "___ père s'appelle Marc.", translation: "My father's name is Marc.",
    explanation: "“My” + a masculine singular noun (père) → mon. The set mon/ma/mes all mean “my”; you pick by the noun." },
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "Voici ___ frère.", translation: "Here is my brother.",
    explanation: "frère is masculine singular → mon frère. (ma/mes would be wrong: ma is for feminine, mes for plural.)" },
  { verb: "possessif-mon", subject: "ma", answer: "ma", prompt: "___ mère est médecin.", translation: "My mother is a doctor.",
    explanation: "mère is feminine singular → ma. Same “my”, but the feminine form is ma." },
  { verb: "possessif-mon", subject: "ma", answer: "ma", prompt: "J'aime ___ voiture.", translation: "I love my car.",
    explanation: "voiture is feminine singular → ma voiture. The owner (me) doesn't change the form — the noun does." },
  { verb: "possessif-mon", subject: "mes", answer: "mes", prompt: "___ parents habitent à Lyon.", translation: "My parents live in Lyon.",
    explanation: "parents is plural → mes. mes is “my” for ANY plural noun, masculine or feminine." },
  { verb: "possessif-mon", subject: "mes", answer: "mes", prompt: "Où sont ___ clés ?", translation: "Where are my keys?",
    explanation: "clés is plural → mes clés. Plural always takes mes." },
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "___ amie est française.", translation: "My friend (f.) is French.",
    explanation: "amie is feminine, but it starts with a vowel → use the MASCULINE form mon (not ma) for easier pronunciation: mon amie." },
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "___ école est grande.", translation: "My school is big.",
    explanation: "école is feminine, but begins with a vowel → mon école (the masculine form is used before a vowel)." },
  { verb: "possessif-mon", subject: "ma", answer: "ma", prompt: "C'est ___ sœur.", translation: "This is my sister.",
    explanation: "sœur is feminine singular (consonant sound) → ma sœur." },
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "___ chien est noir.", translation: "My dog is black.",
    explanation: "chien is masculine singular → mon chien." },
  { verb: "possessif-mon", subject: "mes", answer: "mes", prompt: "J'aime ___ chats.", translation: "I love my cats.",
    explanation: "chats is plural → mes chats." },
  { verb: "possessif-mon", subject: "ma", answer: "ma", prompt: "___ maison est à la campagne.", translation: "My house is in the countryside.",
    explanation: "maison is feminine singular → ma maison." },
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "Je cherche ___ téléphone.", translation: "I'm looking for my phone.",
    explanation: "téléphone is masculine singular → mon téléphone." },
  { verb: "possessif-mon", subject: "mes", answer: "mes", prompt: "___ amis sont gentils.", translation: "My friends are kind.",
    explanation: "amis is plural → mes amis. (mes also handles the vowel here — no special masculine/feminine choice in the plural.)" },
  { verb: "possessif-mon", subject: "mon", answer: "mon", prompt: "___ histoire est vraie.", translation: "My story is true.",
    explanation: "histoire is feminine, but starts with a vowel → mon histoire (masculine form before a vowel)." },

  // ---------- TON / TA / TES : your (informal) ----------
  { verb: "possessif-ton", subject: "ton", answer: "ton", prompt: "___ frère est gentil.", translation: "Your brother is kind.",
    explanation: "“Your” (informal) + masculine singular noun → ton. The set ton/ta/tes all mean “your”." },
  { verb: "possessif-ton", subject: "ta", answer: "ta", prompt: "___ sœur est gentille.", translation: "Your sister is kind.",
    explanation: "sœur is feminine singular → ta sœur." },
  { verb: "possessif-ton", subject: "tes", answer: "tes", prompt: "___ parents sont gentils.", translation: "Your parents are kind.",
    explanation: "parents is plural → tes parents. Plural “your” = tes." },
  { verb: "possessif-ton", subject: "ton", answer: "ton", prompt: "Où est ___ livre ?", translation: "Where is your book?",
    explanation: "livre is masculine singular → ton livre." },
  { verb: "possessif-ton", subject: "ta", answer: "ta", prompt: "J'aime ___ voiture.", translation: "I like your car.",
    explanation: "voiture is feminine singular → ta voiture." },
  { verb: "possessif-ton", subject: "tes", answer: "tes", prompt: "Ce sont ___ clés ?", translation: "Are these your keys?",
    explanation: "clés is plural → tes clés." },
  { verb: "possessif-ton", subject: "ton", answer: "ton", prompt: "___ amie est là.", translation: "Your friend (f.) is here.",
    explanation: "amie is feminine but starts with a vowel → ton amie (masculine form before a vowel)." },
  { verb: "possessif-ton", subject: "ton", answer: "ton", prompt: "___ école est grande ?", translation: "Is your school big?",
    explanation: "école is feminine but begins with a vowel → ton école." },
  { verb: "possessif-ton", subject: "ta", answer: "ta", prompt: "___ maison est belle.", translation: "Your house is beautiful.",
    explanation: "maison is feminine singular (consonant sound) → ta maison." },
  { verb: "possessif-ton", subject: "tes", answer: "tes", prompt: "___ chats sont noirs.", translation: "Your cats are black.",
    explanation: "chats is plural → tes chats." },
  { verb: "possessif-ton", subject: "ton", answer: "ton", prompt: "___ chien est gentil.", translation: "Your dog is kind.",
    explanation: "chien is masculine singular → ton chien." },
  { verb: "possessif-ton", subject: "ton", answer: "ton", prompt: "C'est ___ idée.", translation: "It's your idea.",
    explanation: "idée is feminine but starts with a vowel → ton idée (masculine form before a vowel, not ta)." },

  // ---------- SON / SA / SES : his / her / its ----------
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "___ père travaille beaucoup.", translation: "His/Her father works a lot.",
    explanation: "son/sa/ses agree with the NOUN, not the owner. père is masculine singular → son père = his OR her father." },
  { verb: "possessif-son", subject: "sa", answer: "sa", prompt: "___ mère est gentille.", translation: "His/Her mother is kind.",
    explanation: "mère is feminine singular → sa mère = his OR her mother. The form follows the noun, not the owner's gender." },
  { verb: "possessif-son", subject: "ses", answer: "ses", prompt: "___ parents sont à Paris.", translation: "His/Her parents are in Paris.",
    explanation: "parents is plural → ses parents." },
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "Elle aime ___ chien.", translation: "She loves her dog.",
    explanation: "chien is masculine → son chien. Even though the owner is “she”, the noun is masculine, so it's son (not sa)." },
  { verb: "possessif-son", subject: "sa", answer: "sa", prompt: "Il cherche ___ voiture.", translation: "He's looking for his car.",
    explanation: "voiture is feminine → sa voiture. The owner is “he”, but the noun is feminine, so it's sa (not son)." },
  { verb: "possessif-son", subject: "ses", answer: "ses", prompt: "___ amis sont gentils.", translation: "His/Her friends are kind.",
    explanation: "amis is plural → ses amis." },
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "___ amie est belle.", translation: "His/Her friend (f.) is beautiful.",
    explanation: "amie is feminine but starts with a vowel → son amie (masculine form before a vowel)." },
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "___ école est grande.", translation: "His/Her school is big.",
    explanation: "école is feminine but begins with a vowel → son école." },
  { verb: "possessif-son", subject: "sa", answer: "sa", prompt: "___ sœur a vingt ans.", translation: "His/Her sister is twenty.",
    explanation: "sœur is feminine singular → sa sœur." },
  { verb: "possessif-son", subject: "ses", answer: "ses", prompt: "Où sont ___ clés ?", translation: "Where are his/her keys?",
    explanation: "clés is plural → ses clés." },
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "___ chat est noir.", translation: "His/Her cat is black.",
    explanation: "chat is masculine singular → son chat." },
  { verb: "possessif-son", subject: "sa", answer: "sa", prompt: "C'est ___ maison.", translation: "It's his/her house.",
    explanation: "maison is feminine singular → sa maison." },
  { verb: "possessif-son", subject: "ses", answer: "ses", prompt: "Il aime ___ cours.", translation: "He likes his classes.",
    explanation: "Here cours is plural (his classes) → ses cours." },
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "Marie cherche ___ téléphone.", translation: "Marie is looking for her phone.",
    explanation: "téléphone is masculine → son téléphone. The owner is Marie (her), but the noun is masculine → son." },
  { verb: "possessif-son", subject: "son", answer: "son", prompt: "___ histoire est vraie.", translation: "His/Her story is true.",
    explanation: "histoire is feminine but starts with a vowel → son histoire (masculine form before a vowel)." },

  // ---------- NOTRE / NOS : our ----------
  { verb: "possessif-notre", subject: "notre", answer: "notre", prompt: "___ maison est grande.", translation: "Our house is big.",
    explanation: "notre/nos = “our”. notre is used for any SINGULAR noun — there's no masculine/feminine difference. maison (singular) → notre." },
  { verb: "possessif-notre", subject: "notre", answer: "notre", prompt: "___ professeur est gentil.", translation: "Our teacher is kind.",
    explanation: "professeur is singular → notre professeur. notre covers both genders in the singular." },
  { verb: "possessif-notre", subject: "nos", answer: "nos", prompt: "___ parents sont gentils.", translation: "Our parents are kind.",
    explanation: "parents is plural → nos. The only choice with notre/nos is singular (notre) vs plural (nos)." },
  { verb: "possessif-notre", subject: "nos", answer: "nos", prompt: "___ amis sont là.", translation: "Our friends are here.",
    explanation: "amis is plural → nos amis." },
  { verb: "possessif-notre", subject: "notre", answer: "notre", prompt: "Voici ___ voiture.", translation: "Here is our car.",
    explanation: "voiture is feminine, but notre doesn't change for gender → notre voiture." },
  { verb: "possessif-notre", subject: "nos", answer: "nos", prompt: "Où sont ___ clés ?", translation: "Where are our keys?",
    explanation: "clés is plural → nos clés." },
  { verb: "possessif-notre", subject: "notre", answer: "notre", prompt: "___ chien est gentil.", translation: "Our dog is kind.",
    explanation: "chien is singular → notre chien." },
  { verb: "possessif-notre", subject: "nos", answer: "nos", prompt: "___ enfants sont à l'école.", translation: "Our children are at school.",
    explanation: "enfants is plural → nos enfants." },
  { verb: "possessif-notre", subject: "notre", answer: "notre", prompt: "C'est ___ école.", translation: "It's our school.",
    explanation: "école is singular → notre école. notre stays the same before a vowel too (no masculine/feminine swap like mon/ma)." },
  { verb: "possessif-notre", subject: "nos", answer: "nos", prompt: "___ chats sont noirs.", translation: "Our cats are black.",
    explanation: "chats is plural → nos chats." },

  // ---------- VOTRE / VOS : your (formal or plural) ----------
  { verb: "possessif-votre", subject: "votre", answer: "votre", prompt: "___ maison est belle.", translation: "Your house is beautiful.",
    explanation: "votre/vos = “your” (formal or plural “you”). votre is for any SINGULAR noun, both genders → votre maison." },
  { verb: "possessif-votre", subject: "votre", answer: "votre", prompt: "Où est ___ voiture ?", translation: "Where is your car?",
    explanation: "voiture is singular → votre voiture. votre doesn't change for gender." },
  { verb: "possessif-votre", subject: "vos", answer: "vos", prompt: "___ enfants sont gentils.", translation: "Your children are kind.",
    explanation: "enfants is plural → vos enfants. The choice is just singular (votre) vs plural (vos)." },
  { verb: "possessif-votre", subject: "vos", answer: "vos", prompt: "Voici ___ clés.", translation: "Here are your keys.",
    explanation: "clés is plural → vos clés." },
  { verb: "possessif-votre", subject: "votre", answer: "votre", prompt: "___ professeur est gentil.", translation: "Your teacher is kind.",
    explanation: "professeur is singular → votre professeur." },
  { verb: "possessif-votre", subject: "vos", answer: "vos", prompt: "___ amis sont les bienvenus.", translation: "Your friends are welcome.",
    explanation: "amis is plural → vos amis." },
  { verb: "possessif-votre", subject: "votre", answer: "votre", prompt: "C'est ___ idée ?", translation: "Is it your idea?",
    explanation: "idée is singular → votre idée. votre stays the same before a vowel (unlike mon/ton/son)." },
  { verb: "possessif-votre", subject: "vos", answer: "vos", prompt: "Où sont ___ parents ?", translation: "Where are your parents?",
    explanation: "parents is plural → vos parents." },
  { verb: "possessif-votre", subject: "votre", answer: "votre", prompt: "___ chien est gentil.", translation: "Your dog is kind.",
    explanation: "chien is singular → votre chien." },
  { verb: "possessif-votre", subject: "vos", answer: "vos", prompt: "Voici ___ devoirs.", translation: "Here is your homework.",
    explanation: "devoirs is plural in French → vos devoirs." },

  // ---------- LEUR / LEURS : their ----------
  { verb: "possessif-leur", subject: "leur", answer: "leur", prompt: "___ maison est grande.", translation: "Their house is big.",
    explanation: "leur/leurs = “their”. leur is for any SINGULAR noun (no gender difference) → leur maison." },
  { verb: "possessif-leur", subject: "leurs", answer: "leurs", prompt: "___ enfants sont gentils.", translation: "Their children are kind.",
    explanation: "enfants is plural → leurs enfants. The plural form adds -s: leurs." },
  { verb: "possessif-leur", subject: "leur", answer: "leur", prompt: "___ voiture est belle.", translation: "Their car is beautiful.",
    explanation: "voiture is singular → leur voiture. leur covers both genders in the singular." },
  { verb: "possessif-leur", subject: "leurs", answer: "leurs", prompt: "___ amis sont là.", translation: "Their friends are here.",
    explanation: "amis is plural → leurs amis." },
  { verb: "possessif-leur", subject: "leur", answer: "leur", prompt: "C'est ___ professeur.", translation: "It's their teacher.",
    explanation: "professeur is singular → leur professeur." },
  { verb: "possessif-leur", subject: "leurs", answer: "leurs", prompt: "Où sont ___ clés ?", translation: "Where are their keys?",
    explanation: "clés is plural → leurs clés." },
  { verb: "possessif-leur", subject: "leur", answer: "leur", prompt: "___ chien est gentil.", translation: "Their dog is kind.",
    explanation: "chien is singular → leur chien." },
  { verb: "possessif-leur", subject: "leurs", answer: "leurs", prompt: "___ parents habitent ici.", translation: "Their parents live here.",
    explanation: "parents is plural → leurs parents." },
  { verb: "possessif-leur", subject: "leur", answer: "leur", prompt: "C'est ___ école.", translation: "It's their school.",
    explanation: "école is singular → leur école. leur stays the same before a vowel." },
  { verb: "possessif-leur", subject: "leurs", answer: "leurs", prompt: "___ chats sont noirs.", translation: "Their cats are black.",
    explanation: "chats is plural → leurs chats." },

  // ====================================================================
  // DEMONSTRATIVE ADJECTIVES  (ce · cet · cette · ces)  = this / that / these
  //   ce    → masculine singular before a consonant  (ce livre)
  //   cet   → masculine singular before a vowel or silent h  (cet homme)
  //   cette → feminine singular  (cette voiture) — stays cette even before a vowel
  //   ces   → plural, any gender  (ces enfants)
  // ====================================================================

  { verb: "demonstratif", subject: "ce", answer: "ce", prompt: "J'aime ___ livre.", translation: "I like this book.",
    explanation: "livre is masculine singular and starts with a consonant → ce livre." },
  { verb: "demonstratif", subject: "ce", answer: "ce", prompt: "___ chien est gentil.", translation: "This dog is kind.",
    explanation: "chien is masculine singular (consonant) → ce chien." },
  { verb: "demonstratif", subject: "ce", answer: "ce", prompt: "___ film est bon.", translation: "This movie is good.",
    explanation: "film is masculine singular (consonant) → ce film." },
  { verb: "demonstratif", subject: "ce", answer: "ce", prompt: "Je regarde ___ match.", translation: "I'm watching this game.",
    explanation: "match is masculine singular (consonant) → ce match." },
  { verb: "demonstratif", subject: "ce", answer: "ce", prompt: "___ café est très bon.", translation: "This coffee is very good.",
    explanation: "café is masculine singular (consonant) → ce café." },
  { verb: "demonstratif", subject: "cet", answer: "cet", prompt: "___ homme est grand.", translation: "This man is tall.",
    explanation: "homme is masculine but starts with a silent h → cet homme (ce becomes cet before a vowel sound)." },
  { verb: "demonstratif", subject: "cet", answer: "cet", prompt: "___ ami est gentil.", translation: "This friend is kind.",
    explanation: "ami is masculine and starts with a vowel → cet ami." },
  { verb: "demonstratif", subject: "cet", answer: "cet", prompt: "___ enfant joue dehors.", translation: "This child is playing outside.",
    explanation: "enfant is masculine and starts with a vowel → cet enfant." },
  { verb: "demonstratif", subject: "cet", answer: "cet", prompt: "___ examen est demain.", translation: "This exam is tomorrow.",
    explanation: "examen is masculine and starts with a vowel → cet examen." },
  { verb: "demonstratif", subject: "cet", answer: "cet", prompt: "___ hiver est froid.", translation: "This winter is cold.",
    explanation: "hiver is masculine and starts with a vowel → cet hiver." },
  { verb: "demonstratif", subject: "cette", answer: "cette", prompt: "___ voiture est belle.", translation: "This car is beautiful.",
    explanation: "voiture is feminine singular → cette voiture." },
  { verb: "demonstratif", subject: "cette", answer: "cette", prompt: "___ maison est grande.", translation: "This house is big.",
    explanation: "maison is feminine singular → cette maison." },
  { verb: "demonstratif", subject: "cette", answer: "cette", prompt: "Je travaille ___ semaine.", translation: "I'm working this week.",
    explanation: "semaine is feminine singular → cette semaine." },
  { verb: "demonstratif", subject: "cette", answer: "cette", prompt: "___ idée est bonne.", translation: "This idea is good.",
    explanation: "idée is feminine and starts with a vowel — but the FEMININE form never changes: cette idée (only masculine ce → cet)." },
  { verb: "demonstratif", subject: "cette", answer: "cette", prompt: "J'aime ___ pomme.", translation: "I like this apple.",
    explanation: "pomme is feminine singular → cette pomme." },
  { verb: "demonstratif", subject: "cette", answer: "cette", prompt: "___ question est bonne.", translation: "This is a good question.",
    explanation: "question is feminine singular → cette question." },
  { verb: "demonstratif", subject: "ces", answer: "ces", prompt: "___ livres sont à moi.", translation: "These books are mine.",
    explanation: "livres is plural → ces livres. ces is used for every plural, masculine or feminine." },
  { verb: "demonstratif", subject: "ces", answer: "ces", prompt: "___ enfants sont gentils.", translation: "These children are kind.",
    explanation: "enfants is plural → ces enfants." },
  { verb: "demonstratif", subject: "ces", answer: "ces", prompt: "Où sont ___ clés ?", translation: "Where are these keys?",
    explanation: "clés is plural → ces clés." },
  { verb: "demonstratif", subject: "ces", answer: "ces", prompt: "___ chats sont noirs.", translation: "These cats are black.",
    explanation: "chats is plural → ces chats." },
  { verb: "demonstratif", subject: "ces", answer: "ces", prompt: "___ pommes sont bonnes.", translation: "These apples are good.",
    explanation: "pommes is plural → ces pommes." },
  { verb: "demonstratif", subject: "ces", answer: "ces", prompt: "___ étudiants travaillent beaucoup.", translation: "These students work a lot.",
    explanation: "étudiants is plural → ces étudiants." },

  // ====================================================================
  // C'EST  vs  CE SONT   (it is / this is · they are / these are)
  //   c'est   → before a singular noun or an adjective  (c'est un ami · c'est vrai)
  //   ce sont → before a plural noun  (ce sont mes amis)
  // Don't confuse c'est (identifying/defining) with il est (describing a known he/it).
  // ====================================================================

  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ une bonne idée.", translation: "It's a good idea.",
    explanation: "A singular noun (une idée) → c'est. c'est = ce + est, used to identify or define something." },
  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ mon frère.", translation: "This is my brother.",
    explanation: "Singular noun (mon frère) → c'est. Use c'est to point out a single person or thing." },
  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ vrai.", translation: "It's true.",
    explanation: "Before an adjective (vrai) → c'est. c'est + adjective gives a general “it is …”." },
  { verb: "cest", subject: "ce", answer: "ce sont", prompt: "___ mes parents.", translation: "These are my parents.",
    explanation: "A plural noun (mes parents) → ce sont. The plural of c'est is ce sont." },
  { verb: "cest", subject: "ce", answer: "ce sont", prompt: "___ mes amis.", translation: "These are my friends.",
    explanation: "Plural noun (mes amis) → ce sont." },
  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ ma sœur.", translation: "This is my sister.",
    explanation: "Singular noun (ma sœur) → c'est." },
  { verb: "cest", subject: "ce", answer: "ce sont", prompt: "___ des étudiants.", translation: "They are students.",
    explanation: "A plural noun (des étudiants) → ce sont." },
  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ une belle maison.", translation: "It's a beautiful house.",
    explanation: "Singular noun (une maison) → c'est." },
  { verb: "cest", subject: "ce", answer: "ce sont", prompt: "___ les clés de la voiture.", translation: "These are the car keys.",
    explanation: "Plural noun (les clés) → ce sont." },
  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ un bon film.", translation: "It's a good movie.",
    explanation: "Singular noun (un film) → c'est." },
  { verb: "cest", subject: "ce", answer: "c'est", prompt: "___ très bon.", translation: "It's very good.",
    explanation: "Before an adjective (bon) → c'est. Note c'est (general “it”) vs il est (a specific he/it)." },
  { verb: "cest", subject: "ce", answer: "ce sont", prompt: "___ mes enfants.", translation: "These are my children.",
    explanation: "Plural noun (mes enfants) → ce sont." },

  // ====================================================================
  // QUESTIONS   est-ce que  vs  qu'est-ce que
  //   est-ce que    → turns a statement into a yes/no question
  //   qu'est-ce que → asks “what …?”
  // Before a vowel, est-ce que elides to est-ce qu' (est-ce qu'il…); these
  // examples use tu/vous/nous so the answer stays the full form.
  // ====================================================================

  { verb: "question", subject: "est-ce que", answer: "est-ce que", prompt: "___ tu parles français ?", translation: "Do you speak French?",
    explanation: "A yes/no question → est-ce que at the front. It has no meaning of its own; it just signals a question." },
  { verb: "question", subject: "qu'est-ce que", answer: "qu'est-ce que", prompt: "___ tu manges ?", translation: "What are you eating?",
    explanation: "Asking “what” → qu'est-ce que. (qu' = que, the word for “what” here.)" },
  { verb: "question", subject: "est-ce que", answer: "est-ce que", prompt: "___ vous êtes prêt ?", translation: "Are you ready?",
    explanation: "Yes/no question → est-ce que vous êtes prêt." },
  { verb: "question", subject: "qu'est-ce que", answer: "qu'est-ce que", prompt: "___ c'est ?", translation: "What is it?",
    explanation: "“What is it?” = Qu'est-ce que c'est ? — a fixed phrase using qu'est-ce que." },
  { verb: "question", subject: "est-ce que", answer: "est-ce que", prompt: "___ tu as un chien ?", translation: "Do you have a dog?",
    explanation: "Yes/no question → est-ce que tu as un chien. (Before a vowel it would shorten: est-ce qu'il a…)" },
  { verb: "question", subject: "qu'est-ce que", answer: "qu'est-ce que", prompt: "___ tu cherches ?", translation: "What are you looking for?",
    explanation: "Asking “what” → qu'est-ce que tu cherches." },
  { verb: "question", subject: "est-ce que", answer: "est-ce que", prompt: "___ tu es français ?", translation: "Are you French?",
    explanation: "Yes/no question → est-ce que tu es français." },
  { verb: "question", subject: "qu'est-ce que", answer: "qu'est-ce que", prompt: "___ vous aimez ?", translation: "What do you like?",
    explanation: "Asking “what” → qu'est-ce que vous aimez." },
  { verb: "question", subject: "est-ce que", answer: "est-ce que", prompt: "___ tu as faim ?", translation: "Are you hungry?",
    explanation: "Yes/no question → est-ce que tu as faim." },
  { verb: "question", subject: "qu'est-ce que", answer: "qu'est-ce que", prompt: "___ tu regardes ?", translation: "What are you watching?",
    explanation: "Asking “what” → qu'est-ce que tu regardes." },
  { verb: "question", subject: "est-ce que", answer: "est-ce que", prompt: "___ nous sommes en retard ?", translation: "Are we late?",
    explanation: "Yes/no question → est-ce que nous sommes en retard." },
  { verb: "question", subject: "qu'est-ce que", answer: "qu'est-ce que", prompt: "___ tu écoutes ?", translation: "What are you listening to?",
    explanation: "Asking “what” → qu'est-ce que tu écoutes." },

  // ====================================================================
  // MULTI-BLANK across the new topics — verbs mixed with possessives,
  // and demonstratives/c'est mixed with possessives.
  // ====================================================================

  // ---- verb + possessive ----
  { prompt: "Elle ___ ___ chien.", translation: "She has her dog.",
    blanks: [ { verb: "avoir", answer: "a" }, { verb: "possessif-son", answer: "son" } ],
    explanation: "Possession of the dog uses avoir → elle a. chien is masculine, so “her” is son (form follows the noun) → son chien." },
  { prompt: "J'___ ___ clés.", translation: "I have my keys.",
    blanks: [ { verb: "avoir", answer: "ai" }, { verb: "possessif-mon", answer: "mes" } ],
    explanation: "avoir → j'ai; clés is plural, so “my” is mes → mes clés." },
  { prompt: "Nous ___ dans ___ maison.", translation: "We are in our house.",
    blanks: [ { verb: "être", answer: "sommes" }, { verb: "possessif-notre", answer: "notre" } ],
    explanation: "Location uses être → nous sommes; maison is singular, so “our” is notre → notre maison." },
  { prompt: "Tu ___ ___ voiture ?", translation: "Do you have your car?",
    blanks: [ { verb: "avoir", answer: "as" }, { verb: "possessif-ton", answer: "ta" } ],
    explanation: "avoir → tu as; voiture is feminine singular, so “your” is ta → ta voiture." },
  { prompt: "Ils ___ ___ livres.", translation: "They have their books.",
    blanks: [ { verb: "avoir", answer: "ont" }, { verb: "possessif-leur", answer: "leurs" } ],
    explanation: "avoir → ils ont; livres is plural, so “their” is leurs → leurs livres." },
  { prompt: "Il ___ avec ___ amie.", translation: "He is with his friend (f.).",
    blanks: [ { verb: "être", answer: "est" }, { verb: "possessif-son", answer: "son" } ],
    explanation: "être → il est; amie is feminine but starts with a vowel, so use the masculine form son → son amie." },
  { prompt: "Vous ___ ___ devoirs ?", translation: "Do you have your homework?",
    blanks: [ { verb: "avoir", answer: "avez" }, { verb: "possessif-votre", answer: "vos" } ],
    explanation: "avoir → vous avez; devoirs is plural, so “your” is vos → vos devoirs." },
  { prompt: "Je ___ ___ ami.", translation: "I am your friend.",
    blanks: [ { verb: "être", answer: "suis" }, { verb: "possessif-ton", answer: "ton" } ],
    explanation: "être → je suis; ami is masculine, so “your” is ton → ton ami." },

  // ---- demonstrative / c'est + possessive ----
  { prompt: "___ livre est ___ cadeau.", translation: "This book is my gift.",
    blanks: [ { verb: "demonstratif", answer: "Ce" }, { verb: "possessif-mon", answer: "mon" } ],
    explanation: "livre is masculine singular → ce livre (Ce at the start of the sentence). cadeau is masculine → mon cadeau." },
  { prompt: "___ maison est ___ maison.", translation: "This house is our house.",
    blanks: [ { verb: "demonstratif", answer: "Cette" }, { verb: "possessif-notre", answer: "notre" } ],
    explanation: "maison is feminine singular → cette maison; singular → notre maison." },
  { prompt: "___ enfants sont ___ amis.", translation: "These children are my friends.",
    blanks: [ { verb: "demonstratif", answer: "Ces" }, { verb: "possessif-mon", answer: "mes" } ],
    explanation: "enfants is plural → ces enfants; amis is plural → mes amis." },
  { prompt: "___ homme est ___ père.", translation: "This man is my father.",
    blanks: [ { verb: "demonstratif", answer: "Cet" }, { verb: "possessif-mon", answer: "mon" } ],
    explanation: "homme starts with a silent h → cet homme; père is masculine → mon père." },
  { prompt: "___ ___ sœur.", translation: "This is my sister.",
    blanks: [ { verb: "cest", answer: "C'est" }, { verb: "possessif-mon", answer: "ma" } ],
    explanation: "A singular noun → c'est; sœur is feminine singular → ma sœur." },
  { prompt: "___ ___ parents.", translation: "These are my parents.",
    blanks: [ { verb: "cest", answer: "Ce sont" }, { verb: "possessif-mon", answer: "mes" } ],
    explanation: "A plural noun → ce sont; parents is plural → mes parents." },
  { prompt: "___ voiture est ___ cadeau.", translation: "This car is his gift.",
    blanks: [ { verb: "demonstratif", answer: "Cette" }, { verb: "possessif-son", answer: "son" } ],
    explanation: "voiture is feminine singular → cette voiture; cadeau is masculine → son cadeau (his)." },
  { prompt: "___ amis ___ ici.", translation: "My friends are here.",
    blanks: [ { verb: "possessif-mon", answer: "Mes" }, { verb: "être", answer: "sont" } ],
    explanation: "amis is plural → mes amis (Mes at the start); plural subject + être → sont." }
];
