// 100 present-tense fill-in-the-blank examples for ÊTRE and AVOIR.
// Each blank is marked with ___ in `prompt`.
// `explanation` says WHY that form is correct (subject + which verb + agreement).
//
// Present tense reference:
//   être : je suis · tu es · il/elle/on est · nous sommes · vous êtes · ils/elles sont
//   avoir: j'ai · tu as · il/elle/on a · nous avons · vous avez · ils/elles ont

const EXAMPLES = [
  // ---------- ÊTRE : je suis ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ étudiant.", translation: "I am a student.",
    explanation: "“Je” + être → suis. Être is the verb “to be”, and its first-person singular form is always “suis”." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ français.", translation: "I am French.",
    explanation: "“Je” takes “suis” with être. Nationalities use être (the state of being something)." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ fatigué aujourd'hui.", translation: "I am tired today.",
    explanation: "Describing a state (tired) uses être. With “je”, être → suis." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ à la maison.", translation: "I am at home.",
    explanation: "Location (“to be at…”) uses être. “Je” + être → suis." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ prêt à partir.", translation: "I am ready to leave.",
    explanation: "“Ready” is a state described with être. First person → suis." },

  // ---------- ÊTRE : tu es ----------
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ très gentil.", translation: "You are very kind.",
    explanation: "“Tu” + être → es. Describing a quality (kind) uses être." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ en retard.", translation: "You are late.",
    explanation: "“To be late” = être en retard. With “tu”, être → es." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ mon meilleur ami.", translation: "You are my best friend.",
    explanation: "Identifying who someone is uses être. “Tu” → es." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ là ?", translation: "Are you there?",
    explanation: "Presence/location uses être. Second-person singular “tu” → es." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ sûr de toi.", translation: "You are sure of yourself.",
    explanation: "A state of mind (sure) uses être. “Tu” + être → es." },

  // ---------- ÊTRE : il / elle / on est ----------
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ médecin.", translation: "He is a doctor.",
    explanation: "“Il” + être → est. Professions take être with no article (il est médecin)." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle ___ belle.", translation: "She is beautiful.",
    explanation: "“Elle” is third-person singular, so être → est. Adjectives of quality use être." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ en vacances !", translation: "We're on vacation!",
    explanation: "“On” behaves like il/elle (singular), so être → est, even though it means “we” here." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ trois heures.", translation: "It is three o'clock.",
    explanation: "Telling time uses “il est” + the hour. Impersonal “il” → est." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle ___ à Paris cette semaine.", translation: "She is in Paris this week.",
    explanation: "Location uses être. “Elle” (singular) → est." },
  { verb: "être", subject: "Ce", answer: "est", prompt: "C'___ une bonne idée.", translation: "It's a good idea.",
    explanation: "“C'est” (ce + est) identifies/defines something. Ce is singular → est." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ d'accord.", translation: "We agree.",
    explanation: "“Être d'accord” = to agree. “On” conjugates like il/elle → est." },

  // ---------- ÊTRE : nous sommes ----------
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ amis depuis longtemps.", translation: "We have been friends for a long time.",
    explanation: "“Nous” + être → sommes. The nous form of être is irregular: sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ en France.", translation: "We are in France.",
    explanation: "Location uses être. First-person plural “nous” → sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ contents de te voir.", translation: "We are happy to see you.",
    explanation: "Emotion/state (happy) uses être. “Nous” → sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ prêts.", translation: "We are ready.",
    explanation: "Describing readiness uses être. “Nous” + être → sommes." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ lundi aujourd'hui.", translation: "Today is Monday.",
    explanation: "Days of the week can use “nous sommes” (nous sommes lundi). Nous → sommes." },

  // ---------- ÊTRE : vous êtes ----------
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ très aimable.", translation: "You are very kind. (formal)",
    explanation: "“Vous” + être → êtes (note the circumflex). Used for formal “you” or plural." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ les bienvenus.", translation: "You are welcome (here).",
    explanation: "Plural/formal “vous” + être → êtes." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ professeur ?", translation: "Are you a teacher?",
    explanation: "Profession uses être. Formal “vous” → êtes." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Où ___-vous ?", translation: "Where are you?",
    explanation: "Location question uses être. “Vous” → êtes (vous êtes → êtes-vous when inverted)." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ en avance.", translation: "You are early.",
    explanation: "“Être en avance” = to be early. “Vous” → êtes." },

  // ---------- ÊTRE : ils / elles sont ----------
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ américains.", translation: "They are American.",
    explanation: "“Ils” (they, masc./mixed) + être → sont. Nationalities use être." },
  { verb: "être", subject: "Elles", answer: "sont", prompt: "Elles ___ sœurs.", translation: "They are sisters.",
    explanation: "“Elles” (they, fem.) + être → sont. Relationships/identity use être." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Les clés ___ sur la table.", translation: "The keys are on the table.",
    explanation: "“Les clés” is plural (they), so être → sont. Location uses être." },
  { verb: "être", subject: "Elles", answer: "sont", prompt: "Elles ___ en réunion.", translation: "They are in a meeting.",
    explanation: "Plural subject + être → sont. Being somewhere uses être." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ très occupés.", translation: "They are very busy.",
    explanation: "Describing a state (busy) for a plural subject → sont." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Mes parents ___ en voyage.", translation: "My parents are traveling.",
    explanation: "“Mes parents” = plural (ils), so être → sont." },

  // ---------- AVOIR : j'ai ----------
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ un chien.", translation: "I have a dog.",
    explanation: "“J'” + avoir → ai. Possession uses avoir. Je becomes j' before a vowel." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ deux frères.", translation: "I have two brothers.",
    explanation: "Avoir = to have. First person j' → ai." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ une question.", translation: "I have a question.",
    explanation: "“Avoir une question” = to have a question. J' → ai." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ vingt ans.", translation: "I am twenty years old.",
    explanation: "Age uses AVOIR in French, not être: “avoir … ans”. So j'ai, literally “I have 20 years.”" },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ faim.", translation: "I am hungry.",
    explanation: "Hunger uses avoir: “avoir faim” (literally “to have hunger”). J' → ai." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ froid.", translation: "I am cold.",
    explanation: "“Avoir froid” = to be cold (lit. “to have cold”). French uses avoir for this, so j'ai." },

  // ---------- AVOIR : tu as ----------
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ raison.", translation: "You are right.",
    explanation: "“Avoir raison” = to be right (lit. “to have reason”). “Tu” + avoir → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ une belle voiture.", translation: "You have a nice car.",
    explanation: "Possession uses avoir. “Tu” → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ soif ?", translation: "Are you thirsty?",
    explanation: "“Avoir soif” = to be thirsty. With “tu”, avoir → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ le temps ?", translation: "Do you have time?",
    explanation: "Possession of time uses avoir. “Tu” → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ de la chance.", translation: "You are lucky.",
    explanation: "“Avoir de la chance” = to be lucky (lit. “to have luck”). “Tu” → as." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ peur du noir.", translation: "You are afraid of the dark.",
    explanation: "“Avoir peur” = to be afraid. French uses avoir, so “tu” → as." },

  // ---------- AVOIR : il / elle / on a ----------
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ les yeux bleus.", translation: "He has blue eyes.",
    explanation: "“Il” + avoir → a. Physical features (having eyes/hair) use avoir." },
  { verb: "avoir", subject: "Elle", answer: "a", prompt: "Elle ___ un bon travail.", translation: "She has a good job.",
    explanation: "Possession uses avoir. “Elle” (singular) → a." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ un examen demain.", translation: "We have an exam tomorrow.",
    explanation: "“On” conjugates like il/elle, so avoir → a, even though it means “we”." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ dix ans.", translation: "He is ten years old.",
    explanation: "Age uses avoir (“avoir … ans”). “Il” → a." },
  { verb: "avoir", subject: "Elle", answer: "a", prompt: "Elle ___ mal à la tête.", translation: "She has a headache.",
    explanation: "“Avoir mal à…” = to have pain / ache. “Elle” → a." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il y ___ un problème.", translation: "There is a problem.",
    explanation: "“Il y a” = there is/are — a fixed expression built on avoir. Impersonal “il” → a." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ besoin d'aide.", translation: "We need help.",
    explanation: "“Avoir besoin de” = to need. “On” conjugates like il/elle → a." },

  // ---------- AVOIR : nous avons ----------
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ une grande famille.", translation: "We have a big family.",
    explanation: "“Nous” + avoir → avons. Possession uses avoir." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ cours à huit heures.", translation: "We have class at eight.",
    explanation: "Having a scheduled thing uses avoir. “Nous” → avons." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ envie de sortir.", translation: "We feel like going out.",
    explanation: "“Avoir envie de” = to feel like / want. “Nous” → avons." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ assez d'argent.", translation: "We have enough money.",
    explanation: "Possession uses avoir. First-person plural “nous” → avons." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ chaud ici.", translation: "We are hot here.",
    explanation: "“Avoir chaud” = to be hot (lit. “to have heat”). “Nous” → avons." },

  // ---------- AVOIR : vous avez ----------
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ des enfants ?", translation: "Do you have children?",
    explanation: "“Vous” + avoir → avez. Possession uses avoir." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ l'heure ?", translation: "Do you have the time?",
    explanation: "Asking for the time uses avoir (“avoir l'heure”). “Vous” → avez." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ raison.", translation: "You are right.",
    explanation: "“Avoir raison” = to be right. Formal/plural “vous” → avez." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ rendez-vous à midi.", translation: "You have an appointment at noon.",
    explanation: "“Avoir rendez-vous” = to have an appointment. “Vous” → avez." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ de la patience.", translation: "You have patience.",
    explanation: "Possession of a quality uses avoir. “Vous” → avez." },

  // ---------- AVOIR : ils / elles ont ----------
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ une maison à la campagne.", translation: "They have a house in the country.",
    explanation: "“Ils” + avoir → ont. Possession uses avoir. (Careful: ils ONT = have, ils SONT = are.)" },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ beaucoup d'amis.", translation: "They have a lot of friends.",
    explanation: "Plural subject + avoir → ont. Don't confuse with “sont” (être)." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ sommeil.", translation: "They are sleepy.",
    explanation: "“Avoir sommeil” = to be sleepy. Third-person plural avoir → ont." },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ trente ans.", translation: "They are thirty years old.",
    explanation: "Age uses avoir (“avoir … ans”). “Elles” → ont." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Les enfants ___ faim.", translation: "The children are hungry.",
    explanation: "“Les enfants” is plural (ils), and “avoir faim” = to be hungry. → ont." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Mes voisins ___ un chat.", translation: "My neighbors have a cat.",
    explanation: "“Mes voisins” = plural (ils). Possession uses avoir → ont." },

  // ---------- MIXED / contrast être vs avoir (the tricky part) ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ content.", translation: "I am happy.",
    explanation: "“Content” is an adjective describing a state → être. “Je” → suis. (Compare: j'ai = I have.)" },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ chaud.", translation: "I am hot.",
    explanation: "Even though English says “I am hot”, French uses avoir for body sensations: “avoir chaud”. J' → ai." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ malade.", translation: "He is sick.",
    explanation: "“Malade” (sick) is a state described with être. “Il” → est." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ de la fièvre.", translation: "He has a fever.",
    explanation: "Having a symptom uses avoir. “Il” → a. (He IS sick = il est malade; he HAS a fever = il a de la fièvre.)" },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ en bonne santé.", translation: "We are in good health.",
    explanation: "“Être en bonne santé” = to be healthy (a state) → être. “Nous” → sommes." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ tort.", translation: "You are wrong.",
    explanation: "“Avoir tort” = to be wrong (lit. “to have wrong”). French uses avoir → “tu” → as." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ en colère ?", translation: "Are you angry?",
    explanation: "“Être en colère” = to be angry (a state) → être. “Vous” → êtes. (But “avoir peur” uses avoir!)" },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ honte.", translation: "They are ashamed.",
    explanation: "“Avoir honte” = to be ashamed. Like many feelings, French uses avoir → ont." },

  // ---------- More variety, all persons ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ désolé.", translation: "I am sorry.",
    explanation: "“Désolé” describes how you are → être. First person → suis." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ besoin de toi.", translation: "I need you.",
    explanation: "“Avoir besoin de” = to need. J' → ai." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ courageux.", translation: "You are brave.",
    explanation: "A character trait (brave) uses être. “Tu” → es." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ les cheveux longs.", translation: "You have long hair.",
    explanation: "Describing physical features uses avoir. “Tu” → as." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle ___ intelligente.", translation: "She is intelligent.",
    explanation: "A quality (intelligent) uses être. “Elle” → est." },
  { verb: "avoir", subject: "Elle", answer: "a", prompt: "Elle ___ un nouveau téléphone.", translation: "She has a new phone.",
    explanation: "Possession uses avoir. “Elle” → a." },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ prêts à commencer.", translation: "We are ready to start.",
    explanation: "“On” conjugates like il/elle → est. Readiness is a state → être." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ le temps.", translation: "We have time.",
    explanation: "Possession uses avoir. “On” → a (like il/elle)." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ français.", translation: "We are French.",
    explanation: "Nationality uses être. “Nous” → sommes." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ peur des araignées.", translation: "We are afraid of spiders.",
    explanation: "“Avoir peur (de)” = to be afraid (of). “Nous” → avons." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ sûrs ?", translation: "Are you sure? (plural)",
    explanation: "Certainty (“être sûr”) is a state → être. Plural “vous” → êtes." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ tort.", translation: "You are wrong.",
    explanation: "“Avoir tort” = to be wrong. “Vous” → avez." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ en forme.", translation: "They are in good shape.",
    explanation: "“Être en forme” = to be fit. Plural → sont." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ rendez-vous chez le médecin.", translation: "They have a doctor's appointment.",
    explanation: "“Avoir rendez-vous” uses avoir. Plural “ils” → ont." },

  // ---------- Common everyday lines ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ ici depuis ce matin.", translation: "I have been here since this morning.",
    explanation: "Presence/location uses être. “Je” → suis." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ mal aux dents.", translation: "I have a toothache.",
    explanation: "“Avoir mal à…” = to have an ache. J' → ai." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ de retour !", translation: "You're back!",
    explanation: "“Être de retour” = to be back. “Tu” → es." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ un message.", translation: "You have a message.",
    explanation: "Possession uses avoir. “Tu” → as." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il ___ tard.", translation: "It is late.",
    explanation: "“Il est tard” — impersonal “il” + être → est for time/conditions." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ raison cette fois.", translation: "He is right this time.",
    explanation: "“Avoir raison” = to be right. “Il” → a." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ presque arrivés.", translation: "We have almost arrived.",
    explanation: "“Être arrivé” describes a state of arrival → être. “Nous” → sommes." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ deux chats.", translation: "We have two cats.",
    explanation: "Possession uses avoir. “Nous” → avons." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ d'où ?", translation: "Where are you from?",
    explanation: "Origin uses être (“être de…”). “Vous” → êtes." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ faim ?", translation: "Are you hungry?",
    explanation: "“Avoir faim” = to be hungry. “Vous” → avez." },
  { verb: "être", subject: "Elles", answer: "sont", prompt: "Elles ___ jumelles.", translation: "They are twins.",
    explanation: "Identity uses être. “Elles” → sont." },
  { verb: "avoir", subject: "Elles", answer: "ont", prompt: "Elles ___ cours de français.", translation: "They have French class.",
    explanation: "Having a class uses avoir. “Elles” → ont." },

  // ---------- A few more ÊTRE to round out ----------
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ d'accord avec toi.", translation: "I agree with you.",
    explanation: "“Être d'accord” = to agree. “Je” → suis." },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu ___ libre ce soir ?", translation: "Are you free tonight?",
    explanation: "Availability (“être libre”) is a state → être. “Tu” → es." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Le café ___ chaud.", translation: "The coffee is hot.",
    explanation: "An object's temperature as a state uses être. “Le café” (it) → est." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ___ en train de manger.", translation: "We are eating (right now).",
    explanation: "“Être en train de” = to be in the middle of doing. “Nous” → sommes." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous ___ prêts ?", translation: "Are you ready? (plural)",
    explanation: "Readiness is a state → être. Plural “vous” → êtes." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ déjà partis.", translation: "They have already left.",
    explanation: "“Partir” forms its passé composé with être: ils sont partis. Plural → sont." },

  // ---------- A few more AVOIR to round out ----------
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ sommeil.", translation: "I am sleepy.",
    explanation: "“Avoir sommeil” = to be sleepy. J' → ai." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu ___ quel âge ?", translation: "How old are you?",
    explanation: "Age uses avoir (“avoir … ans”). “Tu” → as." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il ___ beaucoup de travail.", translation: "He has a lot of work.",
    explanation: "Possession (of work) uses avoir. “Il” → a." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous ___ un cadeau pour toi.", translation: "We have a gift for you.",
    explanation: "Possession uses avoir. “Nous” → avons." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous ___ de la chance !", translation: "You are lucky!",
    explanation: "“Avoir de la chance” = to be lucky. “Vous” → avez." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ besoin de repos.", translation: "They need rest.",
    explanation: "“Avoir besoin de” = to need. Plural “ils” → ont." },

  // ---------- Final contrast pairs (être vs avoir confusion) ----------
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ___ étudiants.", translation: "They are students.",
    explanation: "Identity/role uses être → sont. (Watch out: ils SONT = are, ils ONT = have.)" },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils ___ des devoirs.", translation: "They have homework.",
    explanation: "Possession uses avoir → ont. Compare with “sont” (être) above — only one letter differs!" },
  { verb: "être", subject: "On", answer: "est", prompt: "On ___ samedi.", translation: "It's Saturday.",
    explanation: "Stating the day uses être (“on est samedi”). “On” → est." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On ___ gagné !", translation: "We won!",
    explanation: "“Gagner” forms its passé composé with avoir: on a gagné. “On” → a." },
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ___ né en hiver.", translation: "I was born in winter.",
    explanation: "“Naître” (to be born) uses être in the passé composé: je suis né. “Je” → suis." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "J'___ mangé une pomme.", translation: "I ate an apple.",
    explanation: "Most verbs (like manger) form the passé composé with avoir: j'ai mangé. J' → ai." },

  // ---------- NEGATIVES: ne … pas (n' before a vowel) ----------
  // The verb form is unchanged — it's just wrapped in ne … pas.
  { verb: "être", subject: "Je", answer: "suis", prompt: "Je ne ___ pas fatigué.", translation: "I am not tired.",
    explanation: "Negation wraps the verb: ne + verb + pas. The form is still “je suis” → Je ne suis pas. (ne stays full before the consonant of “suis”.)" },
  { verb: "être", subject: "Tu", answer: "es", prompt: "Tu n'___ pas en retard.", translation: "You are not late.",
    explanation: "ne becomes n' before a vowel, and “es” starts with a vowel → Tu n'es pas. The verb form is unchanged." },
  { verb: "être", subject: "Il", answer: "est", prompt: "Il n'___ pas content.", translation: "He is not happy.",
    explanation: "n' + est + pas → Il n'est pas. ne elides to n' before the vowel of “est”." },
  { verb: "être", subject: "Ce", answer: "est", prompt: "Ce n'___ pas vrai.", translation: "It's not true.",
    explanation: "“Ce n'est pas” is the negative of “c'est”. ne → n' before “est”." },
  { verb: "être", subject: "Nous", answer: "sommes", prompt: "Nous ne ___ pas prêts.", translation: "We are not ready.",
    explanation: "ne + sommes + pas → Nous ne sommes pas. ne stays full before the consonant of “sommes”." },
  { verb: "être", subject: "Vous", answer: "êtes", prompt: "Vous n'___ pas sûrs.", translation: "You are not sure.",
    explanation: "“êtes” starts with a vowel, so ne → n' → Vous n'êtes pas." },
  { verb: "être", subject: "Ils", answer: "sont", prompt: "Ils ne ___ pas américains.", translation: "They are not American.",
    explanation: "ne + sont + pas → Ils ne sont pas. The form “sont” doesn't change in the negative." },
  { verb: "être", subject: "Elle", answer: "est", prompt: "Elle n'___ pas là.", translation: "She is not here.",
    explanation: "n' + est + pas → Elle n'est pas là." },

  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "Je n'___ pas faim.", translation: "I am not hungry.",
    explanation: "All present-tense avoir forms start with a vowel, so ne → n': Je n'ai pas faim." },
  { verb: "avoir", subject: "Tu", answer: "as", prompt: "Tu n'___ pas raison.", translation: "You are not right.",
    explanation: "n' + as + pas → Tu n'as pas raison. The verb form stays “as”." },
  { verb: "avoir", subject: "Il", answer: "a", prompt: "Il n'___ pas de voiture.", translation: "He doesn't have a car.",
    explanation: "Il n'a pas… Note: after a negative, un/une/des become “de” — “une voiture” → “pas de voiture”." },
  { verb: "avoir", subject: "On", answer: "a", prompt: "On n'___ pas peur.", translation: "We're not afraid.",
    explanation: "“On” conjugates like il/elle → a, and ne → n' before it: On n'a pas peur." },
  { verb: "avoir", subject: "Nous", answer: "avons", prompt: "Nous n'___ pas le temps.", translation: "We don't have time.",
    explanation: "n' + avons + pas → Nous n'avons pas le temps." },
  { verb: "avoir", subject: "Vous", answer: "avez", prompt: "Vous n'___ pas tort.", translation: "You are not wrong.",
    explanation: "n' + avez + pas → Vous n'avez pas tort." },
  { verb: "avoir", subject: "Ils", answer: "ont", prompt: "Ils n'___ pas d'enfants.", translation: "They don't have children.",
    explanation: "Ils n'ont pas… After a negative, “des” becomes “de” (→ d' before a vowel): “des enfants” → “pas d'enfants”." },
  { verb: "avoir", subject: "Je (j')", answer: "ai", prompt: "Je n'___ pas de chien.", translation: "I don't have a dog.",
    explanation: "Je n'ai pas… and “un chien” → “pas de chien” (un/une/des → de in the negative)." }
];
