// Shared French → English word glossary for the tap-a-word hint feature.
// Keys are NORMALIZED: lowercase, accents stripped, apostrophes normalized to ',
// and leading/trailing apostrophes removed — matching wordKey() in script.js.
// Words not present here simply aren't tappable (graceful fallback).

const GLOSSARY = {
  // elisions / fragments left when the verb is the blank
  "j": "I (j' = je)",
  "n": "not (n' = ne)",
  "c": "it / this (c' = ce)",
  "y": "there (il y a = there is)",
  "a": "to / at (à)",

  // pronouns & subjects
  "je": "I",
  "tu": "you (informal)",
  "il": "he / it",
  "elle": "she / it",
  "on": "we / one (informal “we”)",
  "nous": "we / us",
  "vous": "you (formal or plural)",
  "ils": "they (masc. / mixed)",
  "elles": "they (fem.)",
  "ce": "this / it",
  "te": "you (object)",
  "toi": "you (after a preposition)",

  // articles & determiners
  "le": "the (masc.)",
  "la": "the (fem.) / there",
  "les": "the (plural)",
  "un": "a / one (masc.)",
  "une": "a / one (fem.)",
  "des": "some / any",
  "du": "of the / some",
  "de": "of / from",
  "aux": "to the / at the (plural)",
  "mon": "my (masc.)",
  "mes": "my (plural)",
  "cette": "this (fem.)",

  // question words & connectors
  "ou": "where  ·  or (où / ou)",
  "d'ou": "from where",
  "quand": "when",
  "quel": "what / which",
  "que": "that / than",
  "qu'il": "that he",
  "qu'elle": "that she",
  "parce": "because (parce que)",
  "et": "and",
  "mais": "but",
  "avec": "with",
  "pour": "for",
  "chez": "at (someone's place)",
  "en": "in / to",
  "depuis": "since / for",
  "presque": "almost",
  "deja": "already",
  "ensemble": "together",
  "ici": "here",
  "aussi": "also / too",
  "tres": "very",
  "trop": "too / too much",
  "beaucoup": "a lot / many",
  "assez": "enough",
  "ne": "not (ne … pas)",
  "pas": "not (ne … pas)",

  // être / avoir idiom nouns (the “avoir” feelings)
  "faim": "hunger (avoir faim = to be hungry)",
  "soif": "thirst (avoir soif = to be thirsty)",
  "froid": "cold (avoir froid = to be cold)",
  "chaud": "hot / warm (avoir chaud = to be hot)",
  "peur": "fear (avoir peur = to be afraid)",
  "honte": "shame (avoir honte = to be ashamed)",
  "sommeil": "sleepiness (avoir sommeil = to be sleepy)",
  "raison": "reason (avoir raison = to be right)",
  "tort": "wrong (avoir tort = to be wrong)",
  "besoin": "need (avoir besoin de = to need)",
  "envie": "desire (avoir envie de = to feel like)",
  "chance": "luck (avoir de la chance = to be lucky)",
  "mal": "pain / ache (avoir mal = to hurt)",
  "ans": "years (avoir … ans = to be … years old)",
  "age": "age (âge)",

  // states / places with être
  "retard": "lateness (en retard = late)",
  "avance": "advance (en avance = early)",
  "forme": "shape (en forme = fit)",
  "colere": "anger (en colère = angry)",
  "vacances": "vacation / holidays",
  "reunion": "meeting",
  "voyage": "trip (en voyage = traveling)",
  "retour": "return (de retour = back)",
  "sante": "health (en bonne santé = healthy)",
  "train": "train (en train de = in the middle of)",
  "accord": "agreement",
  "d'accord": "okay / agreed",

  // adjectives
  "content": "happy / glad",
  "contente": "happy / glad (fem.)",
  "contents": "happy / glad (plural)",
  "fatigue": "tired",
  "malade": "sick / ill",
  "pret": "ready",
  "prets": "ready (plural)",
  "sur": "sure  ·  on (sûr / sur)",
  "surs": "sure (plural)",
  "libre": "free / available",
  "gentil": "kind / nice",
  "gentille": "kind / nice (fem.)",
  "aimable": "kind / friendly",
  "courageux": "brave",
  "belle": "beautiful (fem.)",
  "intelligent": "intelligent / smart",
  "intelligente": "intelligent / smart (fem.)",
  "occupes": "busy (plural)",
  "bon": "good (masc.)",
  "bonne": "good (fem.)",
  "grande": "big / large (fem.)",
  "nouveau": "new",
  "meilleur": "best / better",
  "mauvaise": "bad (fem.)",
  "longs": "long (plural)",
  "bleus": "blue (plural)",
  "noir": "dark / black",
  "vrai": "true",
  "desole": "sorry",
  "bienvenus": "welcome (plural)",
  "americains": "American (plural)",
  "francais": "French",

  // people & things (nouns)
  "ami": "friend",
  "amis": "friends",
  "d'amis": "of friends",
  "freres": "brothers",
  "sœurs": "sisters",
  "jumelles": "twins (fem.)",
  "enfants": "children",
  "d'enfants": "of children",
  "parents": "parents",
  "voisins": "neighbors",
  "bebe": "baby",
  "famille": "family",
  "medecin": "doctor",
  "professeur": "teacher",
  "etudiant": "student",
  "etudiants": "students",
  "chien": "dog",
  "chat": "cat",
  "chats": "cats",
  "araignees": "spiders",
  "voiture": "car",
  "maison": "house / home",
  "cafe": "coffee / café",
  "telephone": "phone",
  "cadeau": "gift",
  "message": "message",
  "cles": "keys",
  "table": "table",
  "pomme": "apple",
  "idee": "idea",
  "question": "question",
  "probleme": "problem",
  "examen": "exam",
  "cours": "class / course",
  "devoirs": "homework",
  "travail": "job / work",
  "argent": "money",
  "d'argent": "of money",
  "patience": "patience",
  "repos": "rest",
  "aide": "help",
  "d'aide": "of / for help",
  "campagne": "countryside",
  "france": "France",
  "paris": "Paris",
  "humeur": "mood",
  "rendez": "appointment (rendez-vous)",

  // body
  "cheveux": "hair",
  "yeux": "eyes",
  "dents": "teeth",
  "tete": "head",
  "fievre": "fever",

  // time
  "matin": "morning",
  "soir": "evening / tonight",
  "midi": "noon",
  "demain": "tomorrow",
  "aujourd'hui": "today",
  "hiver": "winter",
  "lundi": "Monday",
  "samedi": "Saturday",
  "semaine": "week",
  "fois": "time (cette fois = this time)",
  "heures": "hours / o'clock",
  "l'heure": "the time",
  "temps": "time / weather",
  "tard": "late",
  "longtemps": "a long time",

  // numbers
  "deux": "two",
  "trois": "three",
  "huit": "eight",
  "dix": "ten",
  "vingt": "twenty",
  "trente": "thirty",

  // verbs (infinitives / participles that appear filled, not as blanks)
  "commencer": "to start",
  "manger": "to eat",
  "mange": "eaten (past participle)",
  "sortir": "to go out",
  "partir": "to leave",
  "partis": "left / gone (plural)",
  "voir": "to see",
  "gagne": "won (past participle)",
  "arrives": "arrived (plural)"
};
